log-level = 'info'
log-file = ''

[server]
sync-check = false

[storage]
# related to run path
data-dir = './data-testnet/chaindb'
state-data-dir = './data-testnet/statedb'
state-cache-dir = './data-testnet/cache'
engine = 'rocksdb'

[chain]
# related to current config file
genesis = 'genesis.local-test.json'
p2p-version = 233333333

# 3d
proposal-expiration-duration = 1200_000
# block-producing-interval = '3s'

[chain.parameter]
# in ms, 10min
maintenance-interval = 600_000

# Default: 100, PrivateNet: 10
energy-price = 140
# Default: 10
bandwidth-price = 140


# NOTE: All following are enabled by proposals.
# PrivateNet: true
allow-multisig = true
# PrivateNet: true
allow-adaptive-energy = true
# PrivateNet: true
allow-delegate-resource = true
# PrivateNet: true
allow-duplicate-asset-names = true
# The TVM upgrade
# PrivateNet: true
allow-tvm = true
# PrivateNet: true
allow-tvm-transfer-trc10-upgrade = true
# PrivateNet: true
allow-tvm-constantinople-upgrade = true
# PrivateNet: true
allow-tvm-solidity-059-upgrade = true
# PrivateNet: true
allow-tvm-shielded-upgrade = true
# PrivateNet: true
# TODO: unimplimented
allow-tvm-istanbul-upgrade = false

[producer]
enable = true

[[producer.keypair]]
address = "TPBMeAqZd5JfbomoMX8BPMttSyHx4Notrx"
private-key = "e957181964f4a3d6c0257a0aa57a5e49ae10dd0a3ab9d12ec05f2fb58862cffc"

[graphql]
enable = true
endpoint = "0.0.0.0:3000"

[protocol]
seed-nodes = [
]

[protocol.discovery]
enable = true
persist = true
# udp discovery
endpoint = '0.0.0.0:18888'
#
# advertise-endpoint = ''
active-nodes = []

[protocol.channel]
enable = true
enable-passive = true
enable-active = true
sync-batch-size = 1000
# tcp channel
endpoint = '0.0.0.0:18888'
advertised-endpoint = ''
# connect in any case
active-nodes = [
]
# accept in any case
passive-nodes = []
max-active-connections = 1

[witness]
private-key = ""

[prometheus]
endpoint = '0.0.0.0:23333'

[rocksdb]
# create-if-missing = true
max-open-files = 40960

# max-background-jobs = 8
# max-sub-compactions = 3
# max-manifest-file-size = "128MB"
# wal-recovery-mode = 2
# wal-dir = "/tmp/tron/store"
# wal-ttl-seconds = 0
# wal-size-limit = 0
# enable-statistics = true
# stats-dump-period = "10m"
# compaction-readahead-size = 0
[rocksdb.defaultcf]
compression-per-level = ["no", "no", "lz4", "lz4", "lz4", "zstd", "zstd"]
