name: Rust

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true

            - name: Install nightly toolchain with clippy available
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: nightly-2020-09-26
                  override: true
                  components: rustfmt, clippy

            - name: Install dependencies
              run: sudo apt-get install protobuf-compiler libprotobuf-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev librocksdb-dev

            - name: Cache Rust build
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Cache ztron-params
              id: cache-ztron-params
              uses: actions/cache@v2
              with:
                  path: ./ztron-params
                  key: ztron-params

            - name: Download ztron-params
              if: steps.cache-ztron-params.outputs.cache-hit != 'true'
              run: |
                  ./scripts/download-ztron-params.sh

            - name: Prepare ztron-params for tests
              run: |
                  cp -r ./ztron-params ./ztron/

            # ldd fix: https://users.rust-lang.org/t/cannot-find-ld-when-using-lld/47420
            - name: Run tests
              run: |
                sudo ln -sf /usr/bin/ld.lld-9 /usr/bin/ld.lld
                cargo test --workspace --lib
              env:
                  LD_LIBRARY_PATH: /usr/local/lib
